#!/bin/bash

# shellcheck source=helper.sh
source "./helper.sh"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SETUP_FLAG="$HOME/.config/.dotfiles_setup_complete"

check_setup_flag() {
    [ -f "$SETUP_FLAG" ]
}

create_setup_flag() {
    mkdir -p "$(dirname "$SETUP_FLAG")"
    cat >"$SETUP_FLAG" <<EOF
DELETE THIS AUTOGENERATED FILE TO RESET DOTFILES SETUP STATUS
Date: $(date '+%Y-%m-%d %H:%M:%S')
Execution Directory: $SCRIPT_DIR
EOF
}

update_dotfiles() {
    print_section "Updating git submodules..."

    if ! git submodule update --init --remote --recursive config_dots/; then
        print_error "Failed to update git submodules"
        return 1
    fi

    print_section "Repopulating dotfiles in \$HOME/.config..."

    mkdir -p "$HOME/.config"

    for module_name in "quickshell" "matugen" "niri"; do
        if [ ! -d "$SCRIPT_DIR/config_dots/$module_name" ]; then
            print_error "Submodule $module_name not found. Run 'git submodule update --init' first."
            continue
        fi

        if [ -e "$HOME/.config/$module_name" ] || [ -L "$HOME/.config/$module_name" ]; then
            read -p "$(echo -e "${CYAN}Update $module_name or keep as is? [U/k]: ${NC}")" -n 1 -r
            REPLY=${REPLY:-U}
            echo ""

            if [[ $REPLY =~ ^[Kk]$ ]]; then
                print_info "Keeping existing $module_name"
                continue
            fi

            BACKUP_DIR="$HOME/.config/Dotfiles_backup_$(date +%Y%m%d_%H%M%S)"
            read -p "$(echo -e "${YELLOW}Directory $module_name exists. Backup to $BACKUP_DIR? [Y/n] (selecting 'n' will DELETE it): ${NC}")" -n 1 -r
            REPLY=${REPLY:-Y}
            echo ""
            if [[ $REPLY =~ ^[Yy]$ ]]; then
                mkdir -p "$BACKUP_DIR"
                mv "$HOME/.config/$module_name" "$BACKUP_DIR/$module_name"
                print_success "Backup complete: $BACKUP_DIR/$module_name"
            else
                print_warning "Deleting $module_name without backup..."
                rm -rf "$HOME/.config/$module_name"
            fi
        fi

        print_info "Copying $module_name to ~/.config..."
        if cp -r "$SCRIPT_DIR/config_dots/$module_name" "$HOME/.config/$module_name"; then
            print_success "$module_name copied"
        else
            print_error "Failed to copy $module_name"
            continue
        fi
    done

    echo ""
    print_separator
    print_success "Dotfiles synced..."
    print_separator
    echo ""
}

show_menu() {
    clear
    echo ""
    print_separator
    print_header "        Dotfiles Setup - Already Initialized"
    print_separator
    echo ""
    print_info "Previous setup detected. What would you like to do?"
    echo ""
    echo "  [1] Update dotfiles"
    echo "      └─ Update config_dots submodules + refresh copies"
    echo ""
    echo "  [2] Exit"
    echo ""
    print_separator
    read -p "$(echo -e "${CYAN}Enter your choice [1-2]: ${NC}")" -n 1 -r
    echo ""
    MENU_CHOICE=$REPLY
}

handle_menu_choice() {
    case $MENU_CHOICE in
        1)
            print_info "Updating dotfiles..."
            update_dotfiles
            print_success "Dotfiles update complete!"
            ;;
        2)
            print_info "Exiting..."
            exit 0
            ;;
        *)
            print_error "Invalid choice. Exiting..."
            exit 1
            ;;
    esac
}

full_setup() {
    print_section "Fetching ALL git submodules..."

    if ! git submodule update --init --recursive; then
        print_error "Failed to initialize git submodules"
        exit 1
    fi

    print_section "Copying dotfiles to \$HOME/.config..."

    mkdir -p "$HOME/.config"

    for module_name in "quickshell" "matugen" "niri"; do
        if [ ! -d "$SCRIPT_DIR/config_dots/$module_name" ]; then
            print_error "Submodule $module_name not found. Skipping..."
            continue
        fi

        if [ -e "$HOME/.config/$module_name" ] || [ -L "$HOME/.config/$module_name" ]; then
            BACKUP_DIR="$HOME/.config/Dotfiles_backup_$(date +%Y%m%d_%H%M%S)"
            read -p "$(echo -e "${YELLOW}Directory $module_name exists. Backup to $BACKUP_DIR? [Y/n] (selecting 'n' will DELETE it): ${NC}")" -n 1 -r
            REPLY=${REPLY:-Y}
            if [[ $REPLY =~ ^[Yy]$ ]]; then
                echo ""
                mkdir -p "$BACKUP_DIR"
                mv "$HOME/.config/$module_name" "$BACKUP_DIR/$module_name"
                print_success "Backup complete: $BACKUP_DIR/$module_name"
                echo ""
            else
                echo ""
                print_warning "Deleting $module_name without backup..."
                rm -rf "$HOME/.config/$module_name"
            fi
        fi

        echo ""
        print_info "Copying $module_name to ~/.config..."
        if cp -r "$SCRIPT_DIR/config_dots/$module_name" "$HOME/.config/$module_name"; then
            print_success "$module_name copied..."
        else
            print_error "Failed to copy $module_name"
            continue
        fi
    done

    echo ""
    print_separator
    print_success "Configurations synced..."
    print_separator
    echo ""

    create_setup_flag

    echo ""
    print_separator
    print_success "Dotfiles setup complete..."
    print_success "DONE"
    print_separator
    echo ""
}

main() {
    clear
    echo ""
    print_error "################################################################"
    print_error "#                                                              #"
    print_error "# WARNING: This script will not work on non-Arch distributions #"
    print_error "#                                                              #"
    print_error "################################################################"
    echo ""

    if check_setup_flag; then
        show_menu
        handle_menu_choice
    else
        print_info "First-time setup detected..."
        full_setup
    fi
}

main
